# Generated by Django 3.2.4 on 2023-04-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='isread',
            field=models.BooleanField(default=False),
        ),
    ]
