# Generated by Django 3.2.4 on 2023-04-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_alter_contact_isread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='isread',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='msgdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
