# Generated by Django 4.2 on 2023-04-27 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0005_alter_contact_name_feedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="ans",
        ),
        migrations.CreateModel(
            name="AnsFeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answers", models.CharField(max_length=350)),
                (
                    "questFeed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gym.feedback"
                    ),
                ),
            ],
        ),
    ]
